name: marksheetscanner
description: "A new Flutter project."

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=3.4.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.6
  image_picker: ^1.1.2
  google_mlkit_text_recognition: ^0.13.0
  get: ^4.6.6
  shared_preferences: ^2.3.1
  flutter_screenutil: ^5.9.3
  material_design_icons_flutter: ^7.0.7296
  flutter_svg: ^2.0.10+1
  dio: ^5.6.0
  pdf: ^3.11.1
  path_provider: ^2.1.4
  permission_handler: ^11.3.0
  path: ^1.9.0
  csv: ^6.0.0
  flutter_pdfview: ^1.3.2
  
dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0


flutter:
  uses-material-design: true
  assets:
    - assets/images/
    - assets/svg/
    - assets/fonts/

   
fonts:
    - family: poppins
      fonts:
       - asset: assets/fonts/Poppins-Regular.ttf
       
    - family: poppinsBold
      fonts:
       - asset: assets/fonts/Poppins-SemiBold.ttf

    - family: poppinsMedium
      fonts:
       - asset: assets/fonts/Poppins-Medium.ttf
   
    - family: poppinsItalic
      fonts:
       - asset: assets/fonts/Poppins-SemiBoldItalic.ttf
   
 
