# Generated by Django 5.1 on 2024-08-14 05:05

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='RecognizedText',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(upload_to='recognized_text_csv/')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
